### PR TITLE
Fixed unset insert_final_newline property removing newlines

### PR DESCRIPTION
**Pull request by febLey**
Fixes https://github.com/editorconfig/editorconfig-vscode/issues/169

- [x] Use a meaningful title for the pull request.
- [x] Use meaningful commit messages.
- [x] Run `tsc` w/o errors (same as `npm run compile`).
- [x] Run `npm run lint` w/o errors.

### CODE REVIEW

**Comment by febLey** [comment]
I don't get why these tests are failing. They shouldn't be impacted by this change :|

**Comment by jedmao** [comment]
Travis seems to be acting a bit weird.

**Comment by jedmao** [comment]
I think we're going to have to roll back the PR for now.

**Comment by jedmao** [comment]
Published v0.10.1 in #171 until we come up with a stable solution.

**Comment by jedmao** [comment]
Let's defer to the conversation in https://github.com/editorconfig/editorconfig-vscode/issues/153 to fix this issue.

**Pull request closed without merging**
