### PR TITLE
Clarify installation of `editorconfig`

### PR DESCRIPTION
**Pull request by papb**
Please fill in this template.

- [X] Use a meaningful title for the pull request.
- [X] Use meaningful commit messages.
- [X] Run `tsc` w/o errors (same as `npm run compile`).
- [X] Run `npm run lint` w/o errors.

-----

It is not immediately obvious from the readme that we also need to install the npm module globally. This took me a few minutes to figure out.

See: https://stackoverflow.com/a/48523398/4135063

### CODE REVIEW

**Comment by jedmao** [comment]
You don't need EditorConfig installed globally for this extension to work, as it uses the JS core under the hood.

**Comment by papb** [comment]
@jedmao is this new? Because I am almost sure it didn't work when I installed just the extension in the past.

**Comment by jedmao** [comment]
No. It's been this way since the beginning.

**Comment by papb** [comment]
Hmm, I must have done something else wrong in my first installation then. Thank you!

**Pull request closed without merging**
